Use template where clause to avoid a runtime type test.
Dimillian/RedditOS pull request #14
Opened 2020-08-01 06:09 UTC by jackpal

Hi Thomas,

Here's what I meant by my tweet about saying that I didn't think you needed the runtime type check. The "where" clause turns it into a compile-time type check.

I wasn't able to test this. It builds, but it doesn't look like there's any code in the current project that uses the code that changed, so I don't know if it works or not.

It seems to me that it should work, though. And the assert will at least provide runtime evidence if it's incorrect.

2021-01-01 16:04 UTC, ericlewis approved these changes
Hooray generics!

2021-01-02 06:20 UTC, Dimillian commented
If you login and click on your profile it'll load a `GenericListContent` because it need to displays posts and comments in the same list. With your PR it's not working anymore. It seems like the first initialiser with the where constraints is never called. Maybe something else is missing?

2021-01-03 01:16 UTC, ericlewis requested changes
Doesn't work

2021-01-03 06:21 UTC, jackpal commented
> If you login and click on your profile it'll load a `GenericListContent` because it need to displays posts and comments in the same list. With your PR it's not working anymore. It seems like the first initialiser with the where constraints is never called.
> 
> So it goes in the generic initializer and fail to decode the list.
> 
> Maybe something else is missing?

Are you sure my PR is causing the issue you are seeing? I just forked and built https://github.com/Dimillian/RedditOS on Xcoder 12.3 / MacOS 11.2 beta without my pull reques, and when  I sign in and click on a profile page, I get this infinite spinner:

<img width="476" alt="Screen Shot 2021-01-02 at 10 19 50 PM" src="https://user-images.githubusercontent.com/175575/103473004-b8e60b00-4d48-11eb-9d99-903f341625de.png">
_

2025-08-02 01:05 UTC, closed without merging